only-deploy-tags: &only-deploy-tags
  filters:
    tags:
      only: /.*/
    branches:
      ignore: /.*/

version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node
    steps:
      - run:
          name: Setting version
          command: 
            npm version $CIRCLE_TAG
      - run:
          name: All files
          command: 
            ls
      - run:
          name: Publishing
          command:
            npm publish

workflows:
  version: 2
  # This only runs on deploy tags and not branches
  tagged-build:
    jobs:
      - deploy:
          <<: *only-deploy-tags