version: 2
jobs:
  storybook:
    # working_directory: ~/react-components
    docker:
      - image: circleci/node
    steps:
      - checkout # Needed to grab code

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Installing
          command: 
            yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Building storybook
          command: yarn run build-storybook

  build: 
    # working_directory: ~/react-components
    docker:
      - image: circleci/node
    steps:
      - checkout # Needed to grab code

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Installing
          command: 
            yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/
          paths: .

      - run:
          name: Building
          command: 
            yarn run build

  deploy:
    # working_directory: ~/react-components
    docker:
      - image: circleci/node
    steps:
      - checkout # Needed to grab code
      - run:
          name: Setting git credentials
          command: |
            git config --global user.email "robbieck7@gmail.com"
            git config --global user.name "Robbie Cook"

      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
          
      - run:
          name: Setting version
          command: 
            npm version $CIRCLE_TAG

      - run:
          name: Publishing
          command:
            npm publish

workflows:
  version: 2
  build:
    jobs:
      # - storybook
      - build:
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /^v[0-9]+(\.[0-9]+)*[/]Stage[/]build_.*/
      - deploy:
          requires:
            - build
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /^v[0-9]+(\.[0-9]+)*[/]Stage[/]build_.*/
  build-n-deploy:
    jobs:
      # - storybook
      - build:
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /^v[0-9]+(\.[0-9]+)*[/]Stage[/]build_.*/
      - deploy:
          requires:
            - build
          filters:  # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /^v[0-9]+(\.[0-9]+)*[/]Stage[/]build_.*/
