only-deploy-tags: &only-deploy-tags
  filters:
    tags:
      only: /.*/
    branches:
      ignore: /.*/

version: 2
jobs:
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Testing
          command: 
            yarn run test
  deploy:
    # working_directory: ~/react-components
    docker:
      - image: circleci/node
    steps:
      - checkout # Needed to grab code
      - run:
          name: Installing
          command: 
            yarn install
      - run:
          name: Building
          command: 
            yarn run build
      - run:
          name: Setting git credentials
          command: 
            yarn run build
      - run:
          name: Setting version
          command: 
            npm version from-git --no-git-tag-version
      - run:
          name: Publishing
          command:
            npm publish

workflows:
  version: 2
  # This only runs on deploy tags and not branches
  tagged-build:
    jobs:
      - test
      - deploy:
          <<: *only-deploy-tags
  untagged-build:
    jobs:
      - test
         
