version: 2
jobs:
  storybook:
    # working_directory: ~/react-components
    docker:
      - image: circleci/node
    steps:
      - checkout # Needed to grab code

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Installing
          command: 
            yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - building_storybook:
          yarn run build-storybook

  deploy:
    # working_directory: ~/react-components
    docker:
      - image: circleci/node
    steps:
      - checkout # Needed to grab code

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Installing
          command: 
            yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/
          paths: .

      - run:
          name: Building
          command: 
            yarn run build

      - run:
          name: Setting git credentials
          command: |
            git config --global user.email "robbieck7@gmail.com"
            git config --global user.name "Robbie Cook"

      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
          
      - run:
          name: Setting version
          command: 
            npm version $CIRCLE_TAG

      - run:
          name: Publishing
          command:
            npm publish

workflows:
  version: 2
  # This only runs on deploy tags and not branches
  tagged-build:
    jobs:
      - deploy:
          filters:
            tags:
              only: /.*/
            branches:
              only: 
                - master

