only-deploy-tags: &only-deploy-tags
  filters:
    tags:
      only: /v*/
    branches:
      ignore: /.*/

version: 2
jobs:
  deploy:
    steps:
      - run:
          name: Echo tag
          command: |
            echo $CIRCLE_TAG

workflows:
  version: 2
  # This runs on non-tag pushes
  untagged-build:
    jobs:
      - build
  # This only runs on deploy tags and not branches
  tagged-build:
    jobs:
      - deploy:
          <<: *only-deploy-tags